author: "Nico Rodsevich <nicorodsevich@gmail.com>"
description: "A pubspec authoring tool. (forked from pen)"
homepage: "https://github.com/Rodsevich/pen"
name: "pen"
version: "0.1.8"
dependencies:
  ansicolor: ^0.0.9
  contrast: ">=0.1.1 <0.2.0"
  path: ">=1.3.0 <2.0.0"
  prompt: ">=0.1.7 <0.2.0"
  pub_package_data: ^0.0.1
  pub_semver: ">=1.1.0 <2.0.0"
  quiver: ">=0.20.0 <0.27.0"
  source_span: ^1.4.0
  unscripted: "^0.6.0"
  which: ">=0.1.3 <0.2.0"
  yaml: ">=2.0.1+1 <3.0.0"
  pen_api: ^0.1.1
environment:
  sdk: ">=1.8.0 <2.0.0"
executables:
  pen: null
